name: transformx
description: A habit tracking app based on the Atomic Habits
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_icon_button: ^1.0.2
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  firebase_habits_api:
    path: packages/firebase_habits_api
  firebase_track_api:
    path: packages/firebase_track_api
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.5.0
  go_router: ^14.2.0
  habits_api:
    path: packages/habits_api
  habits_repository:
    path: packages/habits_repository
  intl: ^0.19.0
  local_preferences_repository:
    path: packages/local_preferences_repository
  local_storage_habits_api:
    path: packages/local_storage_habits_api
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.1.0
  stats_repository:
    path: packages/stats_repository
  timezone: ^0.9.2  
  track_repository:
    path: packages/track_repository
  
dev_dependencies:
  bloc_test: ^9.1.2
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  mockingjay: ^0.5.0
  mocktail: ^1.0.1  
  very_good_analysis: ^6.0.0
  
flutter:
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/logo/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 800
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 900  

  generate: true

  uses-material-design: true
