name: transformx
description: A habit tracking app based on the Atomic Habits
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.0
  habits_api:
    path: packages/habits_api
  habits_repository:
    path: packages/habits_repository
  intl: ^0.18.0
  local_storage_habits_api:
    path: packages/local_storage_habits_api
  
dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0  
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
