name: track_api
description: A track api which stores the track of the habits performance
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.4.2
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
